#!/usr/bin/env bash
## @file
# @author Ernest Skrzypczyk
# @date 2025.04.17
# @comment

##
# @todo 
#

YAML=${YAML:-bitnet}
PODMAN_COMPOSE="${PODMAN_COMPOSE:-${HOME}/Workspaces/podman-compose/bin/activate}"
POD=${POD:-bitnet-local}
VIRTUALIZATION=${VIRTUALIZATION:-podman}

init() {
	# Load secrets into environment
	local SECRETS="${0##*/}.secrets"
	[ -f "${SECRETS}" ] && source "${SECRETS}"
}

podman-compose-check(){
	command -v podman-compose &>/dev/null && return
	[[ "${VIRTUAL_ENV_PROMPT}" != "(podman-compose)" ]] && source "${PODMAN_COMPOSE}"
}

podman-build(){
	podman-build-0
}

podman-build-0(){
	podman build -t "${YAML}" -f "${YAML}.docker" .
}

podman-build-1(){ ## Build in /tmp
	mkdir -p /tmp/podman/{root,store,var}
	export TMPDIR=/tmp/podman/var
	podman --root /tmp/podman/root --imagestore /tmp/podman/store build -t "${YAML}" -f "${YAML}.docker" .
}

podman-check(){
	echo
}

podman-run(){
	podman-run-0
}

podman-run-0(){
	podman run --rm -v /tmp/bitnet:/io -it localhost/bitnet "${@}"
}

podman-run-1(){
	podman --root /tmp/podman/root --imagestore /tmp/podman/store run --rm -v ./bitnet.history:/tmp/bash.history:ro -e HISTFILE=/tmp/bash.history -v /tmp/bitnet:/io -it localhost/bitnet "${@}"
}

podman-server(){
	podman-server-0
}

podman-server-0(){
	shift
	podman-compose-check
	podman-compose -f "${YAML}.yaml" up
	podman-compose -f "${YAML}.yaml" down
}

podman-server-1(){
	echo
}

podman-server-2(){
	echo
}

podman-shell(){
	shift
	podman exec -it container-server /bin/bash "${@}"
}

docker-check(){
	echo
}

docker-server(){
	echo
}

docker-shell(){
	shift
	sudo docker exec -it container-server /bin/bash "${@}"
}

build(){ #Build image
	${VIRTUALIZATION}-build
}

check(){ #Check services connectivity
	${VIRTUALIZATION}-check
}

run(){ #Run container with a prompt
	${VIRTUALIZATION}-run
}

server(){ #Run container server
	${VIRTUALIZATION}-server
}

shell(){ #Run shell inside container
	${VIRTUALIZATION}-shell
}

usage(){ #Show this information
	echo -e "Usage ${0##*/}: $(grep -Eo '(^[[:alnum:]_-]{1,})\(\)\{' ${0} | grep -Ev -e '-[0-9]*\(' -e '^podman-|^docker-' | tr -d '(){' | tr '\n' '|' | sed 's/|*$//')
$(grep -Eo '(^[[:alnum:]_-]{1,})\(\)\{ #.*' ${0} | sed 's/(){ #/: /' | while read ENTRY; do echo -e "\t${ENTRY}"; done)"
}

CMD=${1:-usage}

[ "${CMD##*/}" != "usage" ] && init

${CMD##*/} ${@}
