#!/usr/bin/env bash
## @file
# @author Ernest Skrzypczyk
# @date 2025.04.17
# @comment

##
# @todo 
#

YAML=${YAML:-bitnet}
PODMAN_COMPOSE_PROVIDER=podman-compose
POD=${POD:-bitnet-local}
[ -f "${0}.virt" ] && source "${0}.virt"
VIRTUALIZATION=${VIRTUALIZATION:-podman}

init(){
	# Load secrets into environment
	local SECRETS="${0##*/}.secrets"
	[ -f "${SECRETS}" ] && source "${SECRETS}"
}

podman-build(){
	podman-build-0
}

podman-build-0(){
	# Regular build
	podman build -t "${YAML}" -f "${YAML}.docker" .
}

podman-build-1(){
	# Build image in /tmp
	mkdir -p /tmp/podman/{root,store,var}
	export TMPDIR=/tmp/podman/var
	podman --root /tmp/podman/root --imagestore /tmp/podman/store build -t "${YAML}" -f "${YAML}.docker" .
}

podman-check(){
	echo
}

podman-run(){
	podman-run-0
}

podman-run-0(){
	# Run local image
	podman run --rm -v ./bitnet.history:/tmp/bash.history:ro -e HISTFILE=/tmp/bash.history -v /tmp/bitnet:/io -it "localhost/${YAML}" "${@}"
}

podman-run-1(){
	# Run local image in /tmp
	podman --root /tmp/podman/root --imagestore /tmp/podman/store run --rm -v ./bitnet.history:/tmp/bash.history:ro -e HISTFILE=/tmp/bash.history -v /tmp/bitnet:/io -it "localhost/${YAML}" "${@}"
}

podman-server(){
	podman-server-0
}

podman-server-0(){
	shift
	podman compose -f "${YAML}.yaml" up
}

podman-shell(){
	shift
	podman exec -it "${YAML}" /bin/bash "${@}"
}

docker-build(){
	docker build -t "${YAML}" -f "${YAML}.docker" .
}

docker-check(){
	echo
}

docker-server(){
	echo
}

docker-shell(){
	shift
	sudo docker exec -it "${YAML}" /bin/bash "${@}"
}

# Meta functions

build(){ #Build image
	${VIRTUALIZATION}-build
}

check(){ #Check services connectivity
	${VIRTUALIZATION}-check
}

run(){ #Run container with a prompt
	${VIRTUALIZATION}-run
}

server(){ #Run container server
	${VIRTUALIZATION}-server
}

shell(){ #Run shell inside container
	${VIRTUALIZATION}-shell
}

virtualization(){ #Get current/Set virtualization backend [docker|podman]
	[ $# -gt 1 ] && echo -e "export VIRTUALIZATION=${2}" > "${0}.virt" && VIRTUALIZATION="${2}" && echo "${VIRTUALIZATION}" && return
	echo ${VIRTUALIZATION}
}

usage(){ #Show this information
	echo -e "Usage ${0##*/}: $(grep -Eo '(^[[:alnum:]_-]{1,})\(\)\{' ${0} | grep -Ev -e '-[0-9]*\(' -e '^podman-|^docker-' | tr -d '(){' | tr '\n' '|' | sed 's/|*$//')
$(grep -Eo '(^[[:alnum:]_-]{1,})\(\)\{ #.*' ${0} | sed 's/(){ #/: /' | while read ENTRY; do echo -e "\t${ENTRY}"; done)"
}

CMD=${1:-usage}

[ "${CMD##*/}" != "usage" ] && init

${CMD##*/} ${@}
