name: Docker and Podman Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - uses: docker/setup-buildx-action@v3

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build with Docker using executable
      run: VIRTUALIZATION=docker ./bitnet build

    - name: Build directly with Docker
      run: docker build --file bitnet.docker --tag bitnet:$(printf '%s.%s\n' "$(git rev-list --count "${1-HEAD}")" "$(git rev-parse --short "${1-HEAD}")") .

    - name: Build with Podman using executable
      run: VIRTUALIZATION=podman ./bitnet build
                
    - name: Build directly with Podman
      run: podman build --file bitnet.docker --tag bitnet:$(printf '%s.%s\n' "$(git rev-list --count "${1-HEAD}")" "$(git rev-parse --short "${1-HEAD}")") .
