name: Docker and Podman Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - uses: docker/setup-buildx-action@v3

    - name: Build with Docker
      run: VIRTUALIZATION=docker ./bitnet build && docker build --file bitnet.docker --tag bitnet:$(printf '%s.%s\n' "$(git rev-list --count "${1-HEAD}")" "$(git rev-parse --short "${1-HEAD}")") .

  build-podman:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build with Podman
      if: ${{ false }}
      run: VIRTUALIZATION=podman ./bitnet build && podman build --file bitnet.docker --tag bitnet:$(printf '%s.%s\n' "$(git rev-list --count "${1-HEAD}")" "$(git rev-parse --short "${1-HEAD}")") .
